/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Enum.java to edit this template
 */
package komunikacija;

import java.io.Serializable;

/**
 *
 * @author Korisnik
 */
public enum Operacija{
    PRIJAVA, UCITAJ_MENADZERE, UCITAJ_STRUCNE_SPREME, UCITAJ_MSS, UCITAJ_MESTA, UCITAJ_VRSTA_AKTIVNOSTI, UCITAJ_PROJEKTE, UCITAJ_SPONZORE, UCITAJ_MENADZERE_FILTER, UCITAJ_MESTA_FILTER, UCITAJ_SPONZOR_FILTER, UCITAJ_SS_FILTER, UCITAJ_VAKT_FILTER, KREIRAJ_MESTO, OBRISI_MESTO, PROMENI_MESTO, KREIRAJ_SPONZOR, OBRISI_SPONZOR, PROMENI_SPONZOR, PROMENI_STRUCNA_SPREMA, OBRISI_STRUCNA_SPREMA, UBACI_STRUCNA_SPREMA, PROMENI_VRSTA_AKTIVNOSTI, OBRISI_VRSTA_AKTIVNOSTI, KREIRAJ_VRSTA_AKTIVNOSTI, KREIRAJ_MSS, OBRISI_MSS, OBRISI_MENADZER, PROMENI_MENADZER, KREIRAJ_MENADZER
}
